### ISSUE TITLE
Make docker container

### ISSUE THREAD

**Issue by tom-adsfund** [pmonks/cljig#1]
It would be great to have a docker container ready to use for this, just to isolate the tinkering from everything else.

**Comment by pmonks** [comment]
Yeah good idea - happy to throw a super-basic docker script in the repo (or accept one, if you're more experienced with docker than I am!).

One thing I should mention is that this project was a pretty brief little experiment that I kind of abandoned for a variety of reasons, and there are better alternatives out there (such as [babashka + add-deps](https://book.babashka.org/#babashkadeps)).

**Comment by tom-adsfund** [comment]
Excellent, I didn't know about add-deps, thanks for mentioning it! I guess there's no special reason to dockerize this one then. I guess you could just add a note that people could use add-deps, that way you won't get a random issue raised again!
